---
- name: make sure python pip is installed
  become: yes
  become_method: sudo
  apt: pkg=python-pip state=latest
  tags: git

- name:  install pip
  pip :
    name : pexpect
  become: yes
  become_method: sudo
