---
- name: download cf-cli
  become: yes
  become_method: sudo
  get_url: >
    url={{ installfile_url }}
    dest=/tmp/cf-cli.deb
    owner=root
    group=root
    mode=0755

- name: install cf-cli
  become: yes
  become_method: sudo
  command: "dpkg -i /tmp/cf-cli.deb"
