---
- name: make sure python-dev is installed
  become: yes
  become_method: sudo
  apt: pkg=python-dev state=latest
  tags: python-dev

- name: make sure python pip is installed
  become: yes
  become_method: sudo
  apt: pkg=python-pip state=latest
  tags: pip

- name:  install awscli
  become: yes
  become_method: sudo
  pip :
    name : awscli
    state: latest
